apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: chrome
  name: chrome
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chrome
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/devstack-default: "true"
        io.kompose.service: chrome
    spec:
      containers:
        - image: edxops/chrome:latest
          name: edx.devstack.chrome
          ports:
            - containerPort: 5900
              hostPort: 15900
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /edx/app/edxapp/edx-platform/common/test/data
              name: chrome-claim0
      hostname: chrome.devstack.edx
      restartPolicy: Always
      volumes:
        - name: chrome-claim0
          persistentVolumeClaim:
            claimName: chrome-claim0
status: {}
