version: "2.1"

services:
  registrar:
    command: bash -c 'source /edx/app/registrar/registrar_env && while true; do python /edx/app/registrar/registrar/manage.py runserver 0.0.0.0:18734; sleep 2; done'
    container_name: edx.devstack.registrar
    hostname: registrar.devstack.edx
    depends_on:
      - mysql
      - memcached
    # Allows attachment to the registrar service using 'docker attach <containerID>'.
    stdin_open: true
    tty: true
    environment:
      DB_HOST: edx.devstack.mysql
      DB_NAME: registrar
      DB_PORT: 3306
      DB_USER: registrar001
      DB_PASSWORD: password
      LMS_HOST: http://localhost:18000
      MEMCACHE_HOST: edx.devstack.memcached
    image: edxops/registrar:${OPENEDX_RELEASE:-latest}
    ports:
      - "18734:18734"
    volumes:
      - /edx/var/registrar/
