apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: memcached
  name: memcached
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: memcached
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/devstack-default: "true"
        io.kompose.service: memcached
    spec:
      containers:
        - image: memcached:1.5.10-alpine
          name: edx.devstack.memcached
          resources: {}
      hostname: memcached.devstack.edx
      restartPolicy: Always
status: {}
