# This file contains configuration common too all microfrontends

version: "2.1"

services:
  microfrontend:
    command: bash -c 'npm install && npm run start'
    image: node:12
    environment:
      - NODE_ENV=development
