apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: schema-registry
  name: schema-registry
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: schema-registry
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/devstack-default: "true"
        io.kompose.service: schema-registry
    spec:
      containers:
        - env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: schema-registry.devstack.edx
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: edx.devstack.kafka:29092
            - name: SCHEMA_REGISTRY_LISTENERS
              value: http://0.0.0.0:8081
          image: confluentinc/cp-schema-registry:6.2.1
          name: edx.devstack.schema-registry
          ports:
            - containerPort: 8081
              hostPort: 8081
              protocol: TCP
          resources: {}
      hostname: schema-registry.devstack.edx
      restartPolicy: Always
status: {}
