#!/usr/bin/expect -f
# Test that dev.pull (bare) prompts before continuing

set timeout 15

spawn make dev.pull

expect {
    "Are you sure you want to run this command" {}
    timeout { puts timeout; exit 1 }
    eof { puts EOF; exit 1 }
}
send "\n"

expect {
    "Pulling lms" {}
    timeout { puts timeout; exit 1 }
    eof { puts EOF; exit 1 }
}

# Send ^C, don't wait for it to finish
send \x03
