name: Add new issues to appropriate GitHub Projects

on:
  issues:
    types:
      - opened

jobs:
  add_to_arch_bom_board:
    uses: openedx/.github/.github/workflows/add-issue-to-a-project.yml@master
    secrets:
      GITHUB_APP_ID: ${{ secrets.GRAPHQL_AUTH_APP_ID }}
      GITHUB_APP_PRIVATE_KEY: ${{ secrets.GRAPHQL_AUTH_APP_PEM }}
    with:
      ORGANIZATION: edx
      PROJECT_NUMBER: 11
