name: Add comment
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'bug'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@2cbfe8b17bb3ba59cdb477ae1d88d14caa96100e
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Follow-up checklist (for Arch-BOM usage)
            - [ ] Is the issue flaky or consistent?
            - [ ] Does it affect multiple people or multiple types of systems?
            - [ ] Update the devstack troubleshooting documentation page if necessary
              - [ ] Do we need a new troubleshooting section?
              - [ ] Did a troubleshooting section already exist, but it wasn't easy to find given the symptoms?
              - [ ] If a recurring issue, should we ticket an automated resolution in place of the doc?
